=== NelsonGL/XML-Project---Bigvir/BigVir2084-Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   targetNamespace="https://datapipelineassignment.org/XML" 
		   elementFormDefault="qualified" 
		   xmlns:fs="https://datapipelineassignment.org/XML">


	<xs:element name ="BigVir2084_database" type="fs:BigVir2084_databasetype">
<!-- ########################### KEYS and KEYREFS ########################### -->
		<xs:key name="doctorID">
			<xs:selector xpath=".//fs:doctor/fs:doctor"/>
			<xs:field xpath="@d_ID"/>
		</xs:key>
		<xs:keyref name="refdoctor" refer="fs:doctorID">
			<xs:selector xpath=".//fs:med_hist/fs:consultation"/>
			<xs:field xpath="@refdoctorID"/>
		</xs:keyref>
		<xs:key name="vaccineID">
			<xs:selector xpath=".//fs:vaccine/fs:vaccine"/>
			<xs:field xpath="@v_ID"/>
		</xs:key>
		<xs:keyref name="refvaccine" refer="fs:vaccineID">
			<xs:selector xpath=".//fs:med_hist/fs:vaccination_stat"/>
			<xs:field xpath="@refvaccineID"/>
		</xs:keyref>
		<xs:key name="citizenID">
			<xs:selector xpath="fs:citizens/fs:citizen"/>
			<xs:field xpath="@c_ID"/>
		</xs:key>
	</xs:element>
<!-- Declaring root fields database type-->
	<xs:complexType name="BigVir2084_databasetype">
		<xs:sequence>
			<xs:element name ="citizens" type="fs:citizensType"/>
			<xs:element name ="doctor" type="fs:doctorType">
			</xs:element>
			<xs:element name ="vaccine" type="fs:vaccineType">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
<!-- ########################### Declaring citizen info fields ########################### -->
	<xs:complexType name="citizensType"> 
		<xs:sequence>
			<xs:element name ="citizen" type="fs:citizenType" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="citizenType">
		<xs:sequence>
			<xs:element name="gen_info" type="fs:gen_infoType"/>
			<xs:element name="med_hist" type="fs:med_histType"/>
			<xs:element name="social_hist"  type="fs:social_histType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="c_ID" type="xs:string" use="required"/>
	</xs:complexType>

<!-- Declaring general information fields -->
	<xs:complexType name="gen_infoType">
		<xs:sequence>
			<xs:element name="lastname" type="xs:string"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="date_of_birth" type="xs:date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="weight" type="xs:string"/>
			<xs:element name="height" type="xs:string"/>
			<xs:element name="address" type="xs:string"/>
			<xs:element name="zipcode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{5}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="phone_number"> 
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{10}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="nationality" type="xs:string"/>
			<xs:element name="email_address">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[^@]+@[^\.]+\..+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- Declaring Medical history fields -->
	<xs:complexType name="med_histType">
		<xs:sequence>
			<xs:element name="consultation" type="fs:consultationType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="hospitalization" type="fs:hospitalizationType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="laboratory"  type="fs:laboratoryType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="vaccination_stat"  type="fs:vaccination_statType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>

	</xs:complexType>
	<!-- Declaring consultations history-->
	<xs:complexType name="consultationType" >
		<xs:sequence>
			<xs:element name="doctor" type="xs:string">
			</xs:element>
			<xs:element name="date_cons" type="xs:date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="doc_speciality" type="xs:string"/>
			<xs:element name="code_cons">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SERIOUS"/>
						<xs:enumeration value="AVERAGE"/>
						<xs:enumeration value="ROUTINE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="country" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="refdoctorID" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Declaring hospitalization history-->
	<xs:complexType name="hospitalizationType">
		<xs:sequence>
			<xs:element name="hospital" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="country" type="xs:string"/>
			<xs:element name="date_hosp" type="xs:date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="hosp_speciality" type="xs:string"/>
			<xs:element name="code_hosp">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SERIOUS"/>
						<xs:enumeration value="AVERAGE"/>
						<xs:enumeration value="ROUTINE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- Declaring laboratory tests history-->
	<xs:complexType name="laboratoryType">
		<xs:sequence>
			<xs:element name="test_type" type="xs:string"/>
			<xs:element name="date_test" type="xs:date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="country" type="xs:string"/>
			<xs:element name="test_result">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="POSITIVE"/>
						<xs:enumeration value="NEGATIVE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- Declaring vaccinations history-->
	<xs:complexType name="vaccination_statType">
		<xs:sequence>
			<xs:element name="vaccine_type" type="xs:string"/>
			<xs:element name="date_vaccination" type="xs:date" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="country" type="xs:string"/>
			<xs:element name="vaccinated" type="xs:boolean"/>
		</xs:sequence>
		<xs:attribute name="refvaccineID" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- Declaring social relations history-->
	<xs:complexType name="social_histType">
		<xs:sequence>
			<xs:element name="event" type="fs:eventType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="eventType" >
		<xs:sequence>
			<xs:element name="event_type" minOccurs="0" maxOccurs="unbounded">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="PUBLIC"/>
						<xs:enumeration value="PRIVATE"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="event_name" type="xs:string"/>
			<xs:element name="event_city" type="xs:string"/>
			<xs:element name="event_country" type="xs:string"/>
			<xs:element name="event_date" type="xs:date" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
<!-- ########################### End of citizen info fields declaration ########################### -->

<!-- ########################### Declaring doctor info fields ########################### -->
	<xs:complexType name="doctorType">
		<xs:sequence>
			<xs:element name="doctor" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="doctor_last_name" type="xs:string"/>
						<xs:element name="doctor_first_name" type="xs:string"/>
						<xs:element name="doctor_speciality" type ="xs:string" />
					</xs:sequence>
					<xs:attribute name="d_ID" type="xs:string" use="required"/>
				</xs:complexType>

			</xs:element>
		</xs:sequence>
	</xs:complexType>
<!-- ########################### End of doctor info fields declaration ###########################-->
	
<!-- ########################### Declaring vaccine info fields ########################### -->
	<xs:complexType name="vaccineType">
		<xs:sequence>
			<xs:element name="vaccine" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="vaccine_name" type="xs:string"/>
						<xs:element name="vaccine_info" type="xs:string"/>
						<xs:element name="vaccine_dose" type ="xs:string" />
					</xs:sequence>
					<xs:attribute name="v_ID" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
<!-- ########################### End of vaccine info fields declaration ########################### -->





</xs:schema>

=== NelsonGL/XML-Project---Bigvir/BigVir2084 - Base.xml
<?xml version="1.0" encoding="utf-8"?>
<fs:BigVir2084_database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:fs="https://datapipelineassignment.org/XML"
xsi:schemaLocation="https://datapipelineassignment.org/XML BigVir2084-Schema.xsd">
	<fs:citizens>
		<fs:citizen c_ID="C00001">
			<fs:gen_info>
				<fs:lastname>LOPEZ</fs:lastname>
				<fs:name>NELSON</fs:name>
				<fs:date_of_birth>1992-07-31</fs:date_of_birth>
				<fs:weight>105</fs:weight>
				<fs:height>192</fs:height>
				<fs:address>REIMS</fs:address>
				<fs:zipcode>51100</fs:zipcode>
				<fs:phone_number>0749205224</fs:phone_number>
				<fs:nationality>VEN</fs:nationality>
				<fs:email_address>nnnn@gmail.com</fs:email_address>
			</fs:gen_info>
			<fs:med_hist>
				<fs:consultation refdoctorID="DTR_1">
					<fs:doctor>DOE JOHN</fs:doctor>
					<fs:date_cons>2021-05-15</fs:date_cons>
					<fs:doc_speciality>TRAUMA</fs:doc_speciality>
					<fs:code_cons>SERIOUS</fs:code_cons>
					<fs:city>REIMS</fs:city>
					<fs:country>FRANCE</fs:country>
				</fs:consultation>
				<fs:hospitalization>
					<fs:hospital>REIMS HOSPITAL</fs:hospital>
					<fs:city>REIMS</fs:city>
					<fs:country>FRANCE</fs:country>
					<fs:date_hosp>2020-12-26</fs:date_hosp>
					<fs:hosp_speciality>TRAUMA</fs:hosp_speciality>
					<fs:code_hosp>SERIOUS</fs:code_hosp>
				</fs:hospitalization>
				<fs:laboratory>
					<fs:test_type>COVID 19</fs:test_type>
					<fs:date_test>2021-04-15</fs:date_test>
					<fs:city>REIMS</fs:city>
					<fs:country>FRANCE</fs:country>
					<fs:test_result>POSITIVE</fs:test_result>
				</fs:laboratory>
				<fs:vaccination_stat refvaccineID="VCOV_1.1">
					<fs:vaccine_type>COVID 19</fs:vaccine_type>
					<fs:date_vaccination>2010-06-30</fs:date_vaccination>
					<fs:city>REIMS</fs:city>
					<fs:country>FRANCE</fs:country>
					<fs:vaccinated>true</fs:vaccinated>
				</fs:vaccination_stat>
			</fs:med_hist>
			<fs:social_hist>
				<fs:event>
					<fs:event_type>PUBLIC</fs:event_type>
					<fs:event_name>MUSIC PARTY</fs:event_name>
					<fs:event_city></fs:event_city>
					<fs:event_country></fs:event_country>
					<fs:event_date>2020-05-30</fs:event_date>
				</fs:event>
			</fs:social_hist>
		</fs:citizen>
		
	</fs:citizens>
	<fs:doctor>
		<fs:doctor d_ID="DTR_1">
			<fs:doctor_last_name>DOE </fs:doctor_last_name>
			<fs:doctor_first_name>JOHN</fs:doctor_first_name>
			<fs:doctor_speciality>Traumatology</fs:doctor_speciality>
		</fs:doctor>
		<fs:doctor d_ID="DTR_2">
			<fs:doctor_last_name>REY</fs:doctor_last_name>
			<fs:doctor_first_name>ADRIANA</fs:doctor_first_name>
			<fs:doctor_speciality>Traumatology</fs:doctor_speciality>
		</fs:doctor>
		<fs:doctor d_ID="DGEN_1">
			<fs:doctor_last_name>ABONDANO</fs:doctor_last_name>
			<fs:doctor_first_name>ALEJANDRO</fs:doctor_first_name>
			<fs:doctor_speciality>Generalist</fs:doctor_speciality>
		</fs:doctor>
		<fs:doctor d_ID="DOTO_1">
			<fs:doctor_last_name>ACERO</fs:doctor_last_name>
			<fs:doctor_first_name>ANDREA</fs:doctor_first_name>
			<fs:doctor_speciality>Otorhinolaryngology</fs:doctor_speciality>
		</fs:doctor>
		<fs:doctor d_ID="DGEN_2">
			<fs:doctor_last_name>MAHECHA</fs:doctor_last_name>
			<fs:doctor_first_name>ANGELA</fs:doctor_first_name>
			<fs:doctor_speciality>Generalist</fs:doctor_speciality>
		</fs:doctor>
	</fs:doctor>
	<fs:vaccine>
		<fs:vaccine v_ID="VCOV_1.1">
			<fs:vaccine_name>Covid 19</fs:vaccine_name>
			<fs:vaccine_info>1st Dose</fs:vaccine_info>
			<fs:vaccine_dose>2</fs:vaccine_dose>
		</fs:vaccine>
		<fs:vaccine v_ID="VCOV_1.2">
			<fs:vaccine_name>Covid 19</fs:vaccine_name>
			<fs:vaccine_info>2nd Dose</fs:vaccine_info>
			<fs:vaccine_dose>2</fs:vaccine_dose>
		</fs:vaccine>
		<fs:vaccine v_ID="VPOL">
			<fs:vaccine_name>Polio</fs:vaccine_name>
			<fs:vaccine_info></fs:vaccine_info>
			<fs:vaccine_dose>1</fs:vaccine_dose>
		</fs:vaccine>
		<fs:vaccine v_ID="VMEN">
			<fs:vaccine_name>Meningitis</fs:vaccine_name>
			<fs:vaccine_info></fs:vaccine_info>
			<fs:vaccine_dose>1</fs:vaccine_dose>
		</fs:vaccine>
		<fs:vaccine v_ID="VRU">
			<fs:vaccine_name>Rubella</fs:vaccine_name>
			<fs:vaccine_info></fs:vaccine_info>
			<fs:vaccine_dose>1</fs:vaccine_dose>
		</fs:vaccine>
		<fs:vaccine v_ID="VTET">
			<fs:vaccine_name>Tetanus</fs:vaccine_name>
			<fs:vaccine_info></fs:vaccine_info>
			<fs:vaccine_dose>1</fs:vaccine_dose>
		</fs:vaccine>

	</fs:vaccine>

</fs:BigVir2084_database>
